CREATE TABLE `cd_card` (
   cd_id MEDIUMINT(10) NOT NULL AUTO_INCREMENT,
   cd_multiverse_id MEDIUMINT(10) UNSIGNED NOT NULL,
   cd_name VARCHAR(150) NOT NULL,

   PRIMARY KEY (cd_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED;
